"use client";

// Client Page to create a new user account

import { useActionState } from "react";
import { SignupForm } from "../../../components/signup-form";
import createUser from "./action_create-user";

export default function Page() {

  // useActionState is a hook to manages the communication between a (server) action and the client (form)
  // Inputs: 
  //  - createUser (server): the server action to be called
  //  - undefined  (server): the initial state of the action
  // Outputs:
  //  - state (client re-rendering): the current state of the action
  //  - formAction (client): the action to be called by the form
  //  - isPending (client): the current boolean state of the action (is it pending?) 
  const [state, formAction, isPending] = useActionState(createUser, undefined);

  // Display Errors: 
  // - When the server action returns an error... ()
  const toast_type = state?.state; //     "pending" | "error" | "success" | undefined
  const toast_message = state?.message;
  const x=3;
    

  // - The error message is displayed as a toast notification



  return (
    // We use the Next <form> tag (generated by useActionState) to handle the form submission
    // The form Tag wraps the (dumb) React component SignupForm
    // It passes the isPending state to the SignupForm component to display the correct button text 
    <div className="flex h-screen w-full items-center justify-center px-4">
      <form action={formAction}>
        {/* <SignupForm isPending={isPending} /> */}
        <SignupForm isPending={isPending} />
      </form>
    </div>
  );
}