version: '3.8'

services:
  postgres:
    build: './db-servers/db-server-dev1'
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
